### ISSUE TITLE
Finish checkout Process

### ISSUE THREAD

**Issue by ghost** [Wildhoney/Magento-on-Angular#111]
I noticed @m3l7 Started the middleware integration for the checkout process which isn't merged into master yet. I am wondering if he completed this yet? I also noticed there has been no angular built yet for this. On your docs it says you support spreedly but I am yet to find that code anywhere.

**Comment by zontafil** [comment]
well, my published version is pretty old. Actually, I have finished a working version with:
- checkout (both guest and with login)
- paypal support
- authorize.net support
- support for simple/configurable products with custom attributes (size, colors etc)
- newsletter integration
- multi store/multi currency support

After 6 months of work, I'm going to deploy next monday a working (and quite beautiful) ecommerce based on moa (if you want to see it, let me know :) )

In the next few weeks I'm going to reorganize a bit the code (some piece of code is bounded to the specific ecommerce I'm building - i.e. I have integrated other plugins like instagram) and publish it.

Since MoA is quite "fatty", my idea would be to split it to a core API service for magento, and a module for angular, so that the it will be more manteinable and it would be possible to use the APIs with other frontend frameworks.
I have to discuss this with the author of MoA

**Comment by joshspivey** [comment]
joshua.spivey@3dsystems.com

**Comment by ghost** [comment]
@m3l7 Awesome would love to see it work. I am going to start migrating this project to angular 2 for seo purposes. Does your version include any angular work? Specifically for checkout?

**Comment by zontafil** [comment]
actually I've made the angular part from scratch, so I've not included it in the MoA repo.
The correct approach here imho is to publish a separate angular module with cart, products, login, newsletter etc. methods.

The complete angular site should be rewritten every time (my preferred way) and, maybe, publish an example complete angular site to a different repo.

Again, I have to reorganize the angular code before I'm gonna publish it.

**Comment by zontafil** [comment]
regarding SEO, we're setting up grunt+phantomjs to serve snapshots of the ecommerce to google (which is quite nice since snaphosts are faster than rebuilding the the page every time, like one would do with angular 2, at least without cache)

**Comment by ghost** [comment]
@m3l7 Well it should be without most of the UI stuff. But it should still have all the angular services and forms hooked up to a view with form validation ect... It takes allot of work connecting all of that stuff.

**Comment by vrkansagara** [comment]
Hey  @shabbirkc and @amijpatel  We need to see this https://github.com/Wildhoney/Magento-on-Angular/issues/111#issuecomment-171808502.
